language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
matrix:
    allow_failures:
        - python: "3.3"

install:
    - pip install pytest

script: PYTHONPATH="." py.test

notifications:
    email: false
